global with sharing class ProductRest {
    global ArticleRest article;

    global class ArticleRest{
        global String articleId;
        global String groupId;
        global String groupName;
        global String subgroupId;
        global String subgroup; 
        global String familyId;
        global String family;
        global String name;
        global String articlePackage;
        global String type;
    }  
}

/*global with sharing class ProductRest {

    global String articleId;
    global String groupId;
    global String groupName;
    global String subgroupId;
    global String subgroup; 
    global String familyId;
    global String family;
    global String name;
    global String articlePackage;
    global String type;
   
}*/